version: '2'
services:
  rs-mariadb:
    container_name: blog-db
    image: mariadb:10.3.7
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_PASSWORD=1111
      - MYSQL_DATABASE=yj-blog
    ports:
      - 3308:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --sql_mode=IGNORE_SPACE --max_connections=10000 --wait_timeout=60000
